version: '3'
services:
  db:
    build: ./containers/db
    command: --default-authentication-plugin=mysql_native_password
    ports:
    - "8008:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: pyoverview_db_1
    ports:
    - "8080:80"

  web:
    build: ./containers/web
    ports:
    - "9090:80"